apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "todo-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "todo-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "todo-frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: NEXT_PUBLIC_API_URL
              value: {{ .Values.env.NEXT_PUBLIC_API_URL | quote }}
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV | quote }}
            - name: NEXT_TELEMETRY_DISABLED
              value: {{ .Values.env.NEXT_TELEMETRY_DISABLED | quote }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: todo-backend-secrets
                  key: DATABASE_URL
            - name: BETTER_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: todo-backend-secrets
                  key: BETTER_AUTH_SECRET
            - name: BETTER_AUTH_URL
              value: "http://localhost:3000"
            - name: NEXT_PUBLIC_BETTER_AUTH_URL
              value: "http://localhost:3000"
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
